name: assets_watcher
description: A command-line app to manege your flutter assets like a pro.
homepage: https://github.com/ishaquehassan/FlutterAssetsIndexer
version: 0.0.1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.6.0
  watcher: ^0.9.7+13
  quartet: ^0.1.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0

executables:
  assets_watcher: main
